name = "GraphMLDatasets"
uuid = "21828b05-d3b3-40ad-870e-a4bc2f52d5e8"
authors = ["Yueh-Hua Tu"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
